apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  name: github-register
  namespace: {{ .Release.Namespace }}
spec:
  authMechs:
  - name: github
    params:
      bearerTokenName: githubToken
      clientid: {{ .Values.github.client_id }}
      defaultObjectClass: inetOrgPerson
      linkToDirectory: "false"
      lookupFilter: (uid=${login})
      noMatchOU: github
      scope: user:read user:email read:org
      uidAttr: login
    required: required
    secretParams:
    - name: secretid
      secretKey: GITHUB_SECRET_ID
      secretName: orchestra-secrets-source
  - name: az
    params:
      rules: custom;github!
    required: required
  - name: map
    params:
      map:
      - uid|user|login
      - mail|static|na
      - givenName|static|na
      - sn|static|na
      - displayName|static|na
      - memberOf|user|groups
    required: required
  level: 10
  root: o=Data